//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public string UserID { get; set; }
        public string Comment1 { get; set; }
        public System.DateTime CommentDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
