//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pause
    {
        public int pauseID { get; set; }
        public Nullable<int> SubscriptionCustomerID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual SubscriptionsCustomer SubscriptionsCustomer { get; set; }
    }
}
